spring:
  datasource-master:
    jdbcUrl: jdbc:mysql://192.168.3.138:3316/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver

  datasource-slave:
    jdbcUrl: jdbc:mysql://192.168.3.138:3326/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
