spring:
  shardingsphere:
    # sharding-jdbc数据源
    datasource:
      common:
        a : 1
      names: ds0,ds1
      # 主
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.3.138:3316/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        password: 123456
        username: root
        type: com.zaxxer.hikari.HikariDataSource
      # 从
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.3.138:3326/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        password: 123456
        username: root
        type: com.zaxxer.hikari.HikariDataSource
    # 规则
    rules:
      replica-query:
        data-sources:
          dsSplitting:
            primary-data-source-name: ds0
            replica-data-source-names: ds1
            load-balancer-name: lb
        load-balancers:
          lb:
            type: ROUND_ROBIN
            props:
              b: 1
    props:
      sql-show: true