spring:
  auto:
    bean:
      kclass:
        enable: true
      student:
        id: 1
        name: xyz
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver