server:
  port: 8089
  
spring:
  application:
    name: foreign-exchange-demo-account
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  scan:
    base-packages: com.xyz.foreign.exchange.account
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost